### ISSUE TITLE
Error in loadNamespace

### ISSUE THREAD

**Issue by FastaKilla** [selesnow/rmytarget#1]
Алексей, добрых суток.

Есть задача приконнектиться к My.target.ru, ваш пакет полностью подходит под задачи, но не ставится, ошибка ниже, увы я только новичек, так что своими силами разобраться не смогу.

Спасибо за модуль.

Downloading GitHub repo selesnow/rmytarget@master
from URL https://api.github.com/repos/selesnow/rmytarget/zipball/master
Installing rmytarget
"C:/Users/PC/DOCUME~1/R/R-34~1.0/bin/x64/R" --no-site-file --no-environ --no-save --no-restore --quiet CMD INSTALL  \
  "C:/Users/PC/AppData/Local/Temp/RtmpwpoEmT/devtools3420375d461/selesnow-rmytarget-34ec6db"  \
  --library="C:/Users/PC/Documents/R/R-3.4.0/library" --install-tests 

* installing *source* package 'rmytarget' ...
** R
** preparing package for lazy loading
Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
  there is no package called 'lubridate'
ERROR: lazy loading failed for package 'rmytarget'
* removing 'C:/Users/PC/Documents/R/R-3.4.0/library/rmytarget'
Installation failed: Command failed (1)

**Comment by selesnow** [comment]
Здравствуйте, судя по ошибке вам требуется предварительно установить пакет lubridate, но я сейчас добавлю его установку в NameSpace.

Попробуйте повторить установку пакета:

```
library(devtools)
install_github('selesnow/rmytarget')
library(rmytarget)
```

**Comment by selesnow** [comment]
Если у вас получилось установить пакет, прошу закрыть ветку.

**Comment by FastaKilla** [comment]
Спасибо
