### ISSUE TITLE
Постоянно отправляет получать токен

### ISSUE THREAD

**Issue by fepsik** [selesnow/rmytarget#12]
При попытке получить стату, отправляет авторизовываться( Все аргументы указываю. Раньше пользовал myTarGetTotalStats и в пару строк получал все необходимые данные, а теперь все сломалось.

Можно обратно myTarGetTotalStats?)

MacOS, если что.

**Comment by selesnow** [comment]
Добрый день, метод который использовался для раьоты с api внутри myTarGetTotalStats не поддерживается с 1 декабря самим MyTarget, поэтому я бы эту функцию не мог вернуть даже если бы очень хотел.

В вашем случае какая то проблема с поиском файла с учётными данными. Вероятнее всего вы просто после авторизации через браузнр копируете код подтверждения, вставляете его в браузер и игнорируете предложение пакета сохранить полученные учётные данные в локальный файл.

Так вот, после введения кода подтверждения в консоле выводится сообщение "Do you want save API credential in local путь к файлу с учётными данными, for use it between R sessions?"

В ответ вам надо ввести yes или y, и все учётные данные сохранятся и вам не потребуется постоянно проходить авторизацию через браузер.

Или же вы неправильно используете аргумент  token_path, о нём можно почитать вот тут - https://github.com/selesnow/rmytarget/releases/tag/v1.1

**Comment by selesnow** [comment]
Если комментарий помог вам решить проблему прошу закрытьтикет.

**Comment by maraevdima** [comment]
Добрый день, Алексей! 
Столкнулся с той же проблемой, не могу решить, помогите, пожалуйста.
Может быть покажете пример как указывать параметр "tokens" что бы постоянно не отправлял получать новый. Токен уже сохранил в файл. Спасибо за вашу работу, очень круто)
![screenshot at 15 20-47-15](https://user-images.githubusercontent.com/46722318/51198998-c2c99600-1906-11e9-9ec7-e28d1106e948.png)
И так тоже выкидывает:
![screenshot at 15 21-13-31](https://user-images.githubusercontent.com/46722318/51200428-8009bd00-190a-11e9-835d-965a812b28df.png)

**Comment by selesnow** [comment]
@maraevdima Здравствуйте!

**Проблема скорее всего возникает по причине того**, что когда пакет спрашивает у вас разрешение на сохранение учётных данных в файл вы ему отказываете, запрос идёт сразу после того, как вы в консоль ввели код подтверждения, и спрашивает он следующее:

`Do you want save API credential in local file token_path/login.rymAuth.RData for use it between R sessions?"`

На данный вопрос необходимо дать подтверждение, введя в консоль одно из следующих значений: y, yes, ok, save.

В противном же случае пакет не сохранит учётные данные в файл, и при следующем обращении к API опять будет запрашивать токен, пока вы не упрётесь в лимит 5 токенов на аккаунт.

**Ещё возможной причиной в вашем случае может быть следующее.**
Смотрите наиболее верный способ указывать полный, а не относительный путь к папке как в вашем случае, например создайте на диске C папку tokens, и в token_path указывайте к ней полный путь т.е. `"C:/tokens"`.

**Comment by maraevdima** [comment]
Алексей, большое спасибо, сейчас попробую!

UPD. В общем не хочет он ходить за токеном в папку (ни по какому пути), а хочет запрашивать новый через браузер. У меня mac os.

UPD_2. Из под винды все работает

**Comment by selesnow** [comment]
а к сожаление с маком не помогу по той простой причине что потестить не на чем даже, но никто не жаловался.

так может все таки на маке проблема с тем что путь условный прописан?

**Comment by maraevdima** [comment]
Перепробовал все варианты с указанием пути. Раз никто не жаловался, значит дело во мне) Спасибо большое за инструмент! (кстати такая же схема с токеном в Директе, на Маке ок работает, и путь указываю на "tokens_yandex" то есть условный)

**Comment by maraevdima** [comment]
@selesnow добрый день, Алексей! Мы нашли ошибку для mac os и linux) Вот она: https://prnt.sc/mmjxj4
Пофиксил у себя, для мака нужно качать отсюда: 
`install_github('maraevdima/rmytarget')`
Как только поправите в своем пакете, сразу удалю, вобщем как скажете)
Тикет можно закрывать.

**Comment by selesnow** [comment]
Благодарю за помощь!
Завтра исправлю обязательно, не знал что на маке так не работает)
Как исправлю сразу отпишусь и закрою тикет.

**Comment by selesnow** [comment]
Ошибку исправил, благодар.
