### ISSUE TITLE
Ошибка в myTarGetCampaignList

### ISSUE THREAD

**Issue by alexandraruslanovna** [selesnow/rmytarget#13]
Прописываю код вызова функции в R script (Power BI)

base_data <- myTarGetStats(date_from   = Sys.Date() - 7,
                           date_to     = Sys.Date(),
                           object_type = "campaigns",
                           metrics = "base",
                           stat_type = "day",
                           login = "Clientname",
                           token_path = "C:/Users/Alexandra/Documents")

Ошибка:
Authorize.
Load token from C:/Users/Alexandra/Documents/Foamline - myTarget.mytar.Auth.RData
Loading object list.
Loading |Ошибка в myTarGetCampaignList(login = "olx_instals", token_path = "C:\\my_develop_workshop\\mytarget_token") :
  Unauthorized (HTTP 401).
Вызовы: myTarGetStats -> do.call -> myTarGetCampaignList -> stop_for_status

**Comment by selesnow** [comment]
Добрый день, я рекомендую всегда писать и отлаживать код не в power bi, а в RStudio.

В вашем случае мне кажется, что вы работаете под агентским аккаунтом, и при авторизации в браузере не переключились на аккаунт рекламодателя, а список рекламных кампаний можно получить только когда вы получили токен для работы именно из рекламного а не агентского аккаунта.

**Comment by alexandraruslanovna** [comment]
Доброе утро!
Прописала эту функцию в RStudio, получила следующие ошибки (в браузере вошла в аккаунт рекламодателя):

Authorize.
Load token from C:/Users/Alexandra/Documents/Clientname.mytar.Auth.RData
Loading object list.
Enter code from browser: OsuV1cnQzkt--------NbS (ввела токен, который отобразился в браузере)
You tokens left for this account: 1
Do you want save API credential in local file (C:\my_develop_workshop\mytarget_token/olx_instals.rymAuth.RData), for use it between R sessions?
y / n (recomedation - y): y
Error in gzfile(file, "wb") : cannot open the connection
In addition: Warning messages:
1: In dir.create(token_path) :
  cannot create dir 'C:\my_develop_workshop\mytarget_token', reason 'No such file or directory'
2: In gzfile(file, "wb") :
  cannot open compressed file 'C:\my_develop_workshop\mytarget_token/olx_instals.mytar.Auth.RData', probable reason 'No such file or directory'

**Comment by alexandraruslanovna** [comment]
Решила попробовать другую функцию, теперь, как я поняла, ошибка прав доступа

camp <- myTarGetCampaignList(login = "Clientname", token_path = "C:/Users/Alexandra/Documents")


Load token from C:/Users/Alexandra/Documents/Clientname.mytar.Auth.RData
Loading |Ошибка в myTarGetCampaignList(login = "Clientname", token_path = 
"C:/Users/Alexandra/Documents") :
  **Forbidden (HTTP 403).**
Вызовы: myTarGetCampaignList -> stop_for_status
Выполнение остановлено

**Comment by selesnow** [comment]
в первом случае пакету не удалось создать файл для того что бы сохранить в нём учётные данные, что бы эту проблему решить надо запустить RStudio с правами администратора, либо в аргумент `token_path` указать папку которая находится **не** на системном диске.

**Comment by alexandraruslanovna** [comment]
Да, верно, были проблемы с доступом к диску.
И теперь новая ошибка
Loading |Ошибка в myTarGetCampaignList(login = "Clientname", token_path = "C:/Users/Alexandra/Documents") :
  Unauthorized (HTTP 401).

Предполагаю что это из за того, что агентский логин грузился, а не рекламный. Мне получается нужно получить новый токен и туда положить?

**Comment by selesnow** [comment]
во втором случае пакет нашел файл с полученными ранее учётными данными которые вы сгенерили именно для работы с агенским аккаунтом

вам надо либо указать любое другое имя в аргумент login, он используется только для создания и поиска файла с учётными данными, при этом далее во всех функциях указывайте такое же значение в аргумент login. Или удалить файл C:/Users/Alexandra/Documents/Clientname.mytar.Auth.RData и по новой выполните функцию, но тут будьте осторожны ведь вы удалите полученный ранее токен, а в mytarget на один аккаунт можно запросить всего 5 токенов, после чего новые токены генериться не будет придётся пакетом удалять из api те которые ранее запросили, а это запутанная процедура.

**Comment by alexandraruslanovna** [comment]
Поменяла Login, да, видимо превышен лимит на токены. 
RStudio запускает следующее предупреждение:

Enter code from browser: Tznr7----NJg02nAGd
WARNING!!! You tokens limit exceeded, delete all previous tokens?
y / n:

**Comment by selesnow** [comment]
ооооо, а это проблема, я то дописал пакет таким образом что бы можно было сбросить все полученные токены, но нигде это не документировал, и даже не планировал.

токены автоматом должны удалиться через месяц в принципе.

если что то можете отвечать пакету в консоли, сначало введите y на вопрос хотите ли вы удалить полученные ранее токены, далее пакет запросит логин аккаунта к которому надо сбросить токены, этот логин можете посмотреть через веб интерфейс вашего агентского аккаунта.

**Comment by selesnow** [comment]
подскажите, у вас получилось сбросить токены?
я обновил пакет там некоторые ошибки.
переустановите его.

если все заработает прошу закрыть тикет

**Comment by alexandraruslanovna** [comment]
Да, все получилось, новая инструкция очень помогла! 
Спасибо большое! Закрываю задачу.
