### ISSUE TITLE
myTarGetStats Error in get(m[1]) : invalid first argument

### ISSUE THREAD

**Issue by Mark-Mediacom** [selesnow/rmytarget#15]
Здравствуйте. Запускаю такой код:

End_Date <- Sys.Date() - 1
Start_date <- today() - day(today())+1

mt_token <- "C:\\Users\\Mark.Yakubov\\Desktop\\Обучение\\R в контексте\\WD\\tokens" # Загрузка уже полученного токена

cab.mt <- myTarGetStats(date_from   = Start_date,
                         date_to     = End_Date,
                         object_type = "campaigns",
                         metrics = "base",
                         stat_type = "summary",
                         login = "2593712310",
                         token_path = mt_token)

получаю ответ в консоли:

Load token from C:\Users\Mark.Yakubov\Desktop\Обучение\R в контексте\WD\tokens/2593712310.mytar.Auth.RData
Loading |===| Done
start-loading------------->
end-loading--------------->
Create result table.
Error in get(m[1]) : invalid first argument

Выскакивает ошибка уже после получения данных, насколько я понимаю. Подскажите, пожалуйста, в чем может быть проблема.

**Comment by selesnow** [comment]
Добрый день, первое, что бросилось в глаза это то, как у вас записан путь, `"C:\Users\Mark.Yakubov\Desktop\Обучение\R в контексте\WD\tokens"`, т.е. по идее уже тут должна выскакивать ошибка т.е. \ является в R символом экранирования, в остальном мне кажется ошибка у меня в пакете, в том, что я не протестировал stat_type = "summary", сегодня постараюсь разобраться.

**Comment by Mark-Mediacom** [comment]
> Добрый день, первое, что бросилось в глаза это то, как у вас записан путь, `"C:\Users\Mark.Yakubov\Desktop\Обучение\R в контексте\WD\tokens"`, т.е. по идее уже тут должна выскакивать ошибка т.е. \ является в R символом экранирования, в остальном мне кажется ошибка у меня в пакете, в том, что я не протестировал stat_type = "summary", сегодня постараюсь разобраться.

Да, в ссылке при копировании сюда почему то "\\" сами поменялись на "\". Github убирает лишние слешы при посте сообщения. В самом коде все правильно внесено. Спасибо за ответ! Буду очень благодарен, если сможете поправить

**Comment by selesnow** [comment]
Добрый день, исправил ошибку о которой вы сообщили, теперь вам необходимо пакет до версии 2.1.3. На данный момент это возможно сделать только с GitHub.

`devtools::install_github("selesnow/rmytarget")`

Ближе к вечеру новую версию можно будет установить так же и с CRAN, я уже отправил обновление на модерацию.

Если всё ок, то прошу закрыть тикет.

**Comment by Mark-Mediacom** [comment]
Все заработало. Спасибо!
