### ISSUE TITLE
Ошибка: `by` can't contain join column `date` which is missing from RHS

### ISSUE THREAD

**Issue by alexandraruslanovna** [selesnow/rmytarget#16]
**Выполняю загрузку всех метрик из клиентского аккаунта MyTarget.**
Предварительно получила токен в RStudio для клиентского логина:
myTarAuth(login = "XXXX")
Enter code from browser: xxxxxx
You tokens left for this account: 4
Do you want save API credential in local file (C:/Users/Alexandra/Documents/XXXX.rymAuth.RData), for use it between R sessions?
y / n (recomedation - y): y
Token saved at C:/Users/Alexandra/Documents/XXXX.mytar.Auth.RData
Далее вызываю функцию myTarGetStats в Rscript (Power BI):
library(rmytarget)
all_data <- myTarGetStats(date_from   = Sys.Date() - 4,
                          date_to     = Sys.Date(),
                          object_type = "campaigns",
                          metrics     = "all",
                          login       = "XXXX",
                          token_path = "C:/Users/Alexandra/Documents")

Получаю **ошибку**
___________________________________________________________________________________
Authorize.
Load token from C:/Users/Alexandra/Documents/XXXX.mytar.Auth.RData
Loading object list.
Load token from C:/Users/Alexandra/Documents/XXXX.RU.mytar.Auth.RData
Loading |=| Done
start-loading------------->
end-loading--------------->
Create result table.
Ошибка: `by` can't contain join column `date` which is missing from RHS
Выполнение остановлено
____________________________________________________________________________________
Можете подсказать в чем проблема? Точно такую же ошибку получаю, когда пытаюсь вызвать эту функцию для агентского аккаунта.

**Comment by selesnow** [comment]
Добрый день, исправил данную ошибку, переустановите пакет с GitHub с помощью команды:

`devtools::install_github('selesnow/rmytarget')`

Если всё ок, то прошу закрыть тикет.

**Comment by alexandraruslanovna** [comment]
Спасибо!
