### ISSUE TITLE
Возможно ли получать статистику в разрезе объявлений?

### ISSUE THREAD

**Issue by Wreitlein** [selesnow/rmytarget#2]
Сейчас, как я понимаю, статистика отдаётся в разрезе кампаний. Можно ли получить её в разрезе объявлений со статистикой и id каждого конкретного объявления?

**Comment by selesnow** [comment]
Добрый день, пакет rmytarget сыроват, на самом деле есть функция myTarGetStats, с помощью которой можно запрашивать статистику в разрезе объявлений:

В аргумент object_id необходимо передать вектор с id объявлений.

```r
myAdsStat <- myTarGetStats(date_from = "2016-08-01",
                            date_to = "2016-08-10",
                            object_type = "pads",
                            object_id = c("00001","00002"),
                            stat_type = "day",
                            auth = myTargetAuth)
```
Что бы было проще с аргументами разобраться можно глянуть в документацию в [этот раздел](https://target.my.com/doc/api/detailed/#resource_statistics).
Попробуйте ей воспользоваться, если что будем совместными усилиями приводить эту функцию к рабочему виду, пока как я уже писал выше пакет недостаточно протестирован и доработан.
