### ISSUE TITLE
Не указано действие при отрицательном результате в ifelse 

### ISSUE THREAD

**Issue by Wreitlein** [selesnow/rmytarget#4]
Здравствуйте, при попытки получить токен ругается на ifelse 
![rstudio](https://user-images.githubusercontent.com/36955869/38030249-bc5b8118-32a0-11e8-89dc-cbeddf43a38f.png)

```
library(rmytarget)
myTargetAuth <- myTarAuth(grant_type = "client_credentials",
                           client_id = "*********",
                           client_secret = "*******")	
Error in ifelse(grant_type == "agency_client_credentials", paste0("&agency_client_name=",  : 
  argument "no" is missing, with no default

**Comment by selesnow** [comment]
Добрый день, по идее исправил ошибку обновите пакет и попробуй ещё раз получить токен:

Для обновление пакета воспользуйтесь следующим кодом:
`devtools::install_github('selesnow/rmytarget')`

**Comment by Wreitlein** [comment]
Спасибо!
