### ISSUE TITLE
Ошибка в функции myTarGetTotalStats

### ISSUE THREAD

**Issue by zkostitsyn** [selesnow/rmytarget#5]
При выполнении функции myTarGetTotalStats всплывает ошибка:
`Error in myTarGetTotalStats(date_to = "2018-04-16", date_to = "2018-04-17",  : 
  formal argument "date_to" matched by multiple actual arguments`

**Comment by selesnow** [comment]
Проблема в том, что дважды указана дата окончания отчётного периода но ни разу не указана дата старта (`date_to = "2018-04-16", date_to = "2018-04-17"`)
Надо прописать вот так:

`myTarGetTotalStats(date_from = "2018-04-16", date_to = "2018-04-17"`
