### ISSUE TITLE
Ошибка content_type

### ISSUE THREAD

**Issue by Tanchik1** [selesnow/rmytarget#7]
Здравствуйте, при попытки получить токен выдает такую ошибку
library(rmytarget)
myTargetAuth <- myTarAuth(grant_type = "client_credentials",
                           client_id = "*********",
                           client_secret = "*********")
Ошибка в content_type(type = "application/x-www-form-urlencoded") :
  не могу найти функцию "content_type"

**Comment by selesnow** [comment]
Добрый день, функция content_type входит в пакет httr, видимо вы работаете с мака, поэтому такая проблема может возникнуть.

Установите пакет httr с помощью команды `install.packages("httr")`, далее подключите пакет `library(httr)`.

И попробуйте ещё раз запустить процесс получения токена.

**Comment by selesnow** [comment]
Просьба, если после установки и подключения httr проблема решилась закрыть тикет.

**Comment by Tanchik1** [comment]
Спасибо, получилось.
