### ISSUE TITLE
Нет client id, secret, есть только Токен

### ISSUE THREAD

**Issue by tytanya** [selesnow/rmytarget#8]
Добрый день. Пытаюсь подключиться к агентскому аккаунту, MyTarget дал только токен, который получаю по ссылке 
http://*.ru/?login=*@agency_client&sk=g**
Чтобы обновить его использую
http://*ru?login=*@agency_client&sk=**&refresh_token=<refresh_token>

Как пользоваться библиотекой, если у меня нет client id и secret? Может их, зная токен, можно как-то получить?

Или как раз client id - Это буквы, которые перед @ стоят, а sk - secret key?

**Comment by selesnow** [comment]
На данный момент я работаю над тем что бы значительно упроситить процесс авторизации в API через библиотеку, ждите релиза в ближайшие дни.

**Comment by selesnow** [comment]
`rmytarget` получил доступ к схеме авторизации Authorization Code Grant, теперь для работы с пакетом не требуются ни clien id ни clien secret.

Подробнее можно узнать [тут](https://github.com/selesnow/rmytarget/releases/tag/v1.1).
