### ISSUE TITLE
Ошибка при установке rmytarget

### ISSUE THREAD

**Issue by edwardJeanx** [selesnow/rmytarget#9]
если у вас при установке вылетает с ошибкой - попробуйте установить сначала **lubridate**
```
install.packages("lubridate")
devtools::install_github("tidyverse/lubridate")
library('lubridate')
```

а потом повторите установку

**Comment by edwardJeanx** [comment]
знал, что пригодится :)

**Comment by selesnow** [comment]
Спасибо, я завтра добавлю автоматическую установку lubridate при запуске установки rmytarget.

**Comment by edwardJeanx** [comment]
Тут такое дело, в первый раз помогло, а на второй не поехало :(

**Comment by selesnow** [comment]
Т.е. по прежнему ошибка?
